// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUINJhxyKKVl0TzE-REPWmdIBiydNmW2A',
    appId: '1:9302027847:web:f58691fd0632fa70d50b62',
    messagingSenderId: '9302027847',
    projectId: 'grupo-4-9824f',
    authDomain: 'grupo-4-9824f.firebaseapp.com',
    storageBucket: 'grupo-4-9824f.appspot.com',
    measurementId: 'G-GQ43GXMJQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp50Tq4moLLGVA5NGcINagKycyP6L09ZE',
    appId: '1:9302027847:android:ae63feabf3bd4a9bd50b62',
    messagingSenderId: '9302027847',
    projectId: 'grupo-4-9824f',
    storageBucket: 'grupo-4-9824f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK05OlV1EJGDM4WZ6b_EuXLazMcK638bs',
    appId: '1:9302027847:ios:c28f267138f367c9d50b62',
    messagingSenderId: '9302027847',
    projectId: 'grupo-4-9824f',
    storageBucket: 'grupo-4-9824f.appspot.com',
    iosBundleId: 'com.example.edge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK05OlV1EJGDM4WZ6b_EuXLazMcK638bs',
    appId: '1:9302027847:ios:5180585cbe678a9cd50b62',
    messagingSenderId: '9302027847',
    projectId: 'grupo-4-9824f',
    storageBucket: 'grupo-4-9824f.appspot.com',
    iosBundleId: 'com.example.edge.RunnerTests',
  );
}
